-- 코드를 작성해주세요


SELECT INFO2.ITEM_ID, INFO2.ITEM_NAME, INFO2.RARITY
FROM ITEM_INFO INFO JOIN ITEM_TREE TREE 
ON INFO.ITEM_ID = TREE.PARENT_ITEM_ID 
JOIN ITEM_INFO INFO2
ON TREE.ITEM_ID = INFO2.ITEM_ID
WHERE INFO.RARITY = 'RARE'
ORDER BY ITEM_ID DESC